### PR TITLE
Added color transition to more info button.

### PR DESCRIPTION
**Pull request by BhandariG29**
Added color transition to more info button in events page on scrolling.

### CODE REVIEW

**Comment by swastkk** [comment]
That's a good start @BhandariG29 , I will advice you to add the Screenshots as well of what changes you have made so that it could be helpful for us as well!

**Comment by BhandariG29** [comment]
okay sir

**Comment by BhandariG29** [comment]
Screenshot 2023-06-24 at 1 21 22 AM

Sir, these are the major changes that i have committed.

**Comment by swastkk** [comment]
> Screenshot 2023-06-24 at 1 21 22 AM
> 
> Sir, these are the major changes that i have committed.

I was saying what changes you have made in the UI, should attach that Screenshot, since it become easy for the Reviewer to have a look at the change and its a nice habit while you will be contributing to the Open Source Community.
Like this 
image

**Comment by swastkk** [comment]
That's a great start, now try to align these buttons inside the div.

**Comment by BhandariG29** [comment]
Understood Sir.

**Comment by swastkk** [comment]
Closing this since entire codebase has been changed!

**Pull request closed without merging**
